data <- read.csv("household_power_consumption.txt", na.strings = "?", sep=";")
data$Date <- as.Date(strptime(data$Date, "%d/%m/%Y"))
sub <- subset(data, data$Date == as.Date("2007-02-01") | data$Date == as.Date("2007-02-02"))
tickmarks <- c(which(sub$Time == "00:00:00"),length(sub$Date))
sub$Sub_metering <- c(rep(0, nrow(sub)-1), max(sub$Sub_metering_1, sub$Sub_metering_2, sub$Sub_metering_3, na.rm = T))
plot(sub$Sub_metering,type = "n", xlab = NA, ylab = "Energy sub metering", axes=F)
lines(sub$Sub_metering_1)
lines(sub$Sub_metering_2, col = "red")
lines(sub$Sub_metering_3, col = "blue")
axis(1, at = tickmarks, labels = c("Thu","Fri","Sat"))
axis(2)
legend("topright", col=c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lwd = 1)
dev.copy(png, file = "plot3.png")
dev.off()