data <- read.csv("household_power_consumption.txt", na.strings = "?", sep=";")
data$Date <- as.Date(strptime(data$Date, "%d/%m/%Y"))
sub <- subset(data, data$Date == as.Date("2007-02-01") | data$Date == as.Date("2007-02-02"))
tickmarks <- c(which(sub$Time == "00:00:00"),length(sub$Date))
par(mfrow = c(2,2))
source("plot2.R")
plot(sub$Voltage,type = "n", xlab = "datatime", xlab = "Voltage", axes=F)
axis(1, at = tickmarks, labels = c("Thu","Fri","Sat"))
axis(2)
lines(sub$Voltage)
source("plot3.R")
plot(sub$Global_reactive_power,type = "n", xlab = "datatime", axes=F)
axis(1, at = tickmarks, labels = c("Thu","Fri","Sat"))
axis(2)
lines(sub$Global_reactive_power)
dev.copy(png, file = "plot4.png")
dev.off()