data <- read.csv("household_power_consumption.txt", na.strings = "?", sep=";")
data$Date <- as.Date(strptime(data$Date, "%d/%m/%Y"))
sub <- subset(data, data$Date == as.Date("2007-02-01") | data$Date == as.Date("2007-02-02"))
tickmarks <- c(which(sub$Time == "00:00:00"),length(sub$Date))
plot(sub$Global_active_power,type = "n", xlab = NA, ylab = "Global Active Power (kilowatts)", axes=F)
axis(1, at = tickmarks, labels = c("Thu","Fri","Sat"))
axis(2)
lines(sub$Global_active_power)
dev.copy(png, file = "plot2.png")
dev.off()